#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

"""
Const

This file contains the constant definitions of all Nextion commands
"""

# function codes
NEX_RET_CMD_FINISHED = 0x01
NEX_RET_EVENT_LAUNCHED = 0x88
NEX_RET_EVENT_UPGRADED = 0x89
NEX_RET_EVENT_TOUCH_HEAD = 0x65
NEX_RET_EVENT_POSITION_HEAD = 0x67
NEX_RET_EVENT_SLEEP_POSITION_HEAD = 0x68
NEX_RET_CURRENT_PAGE_ID_HEAD = 0x66
NEX_RET_STRING_HEAD = 0x70
NEX_RET_NUMBER_HEAD = 0x71
NEX_RET_INVALID_CMD = 0x00
NEX_RET_INVALID_COMPONENT_ID = 0x02
NEX_RET_INVALID_PAGE_ID = 0x03
NEX_RET_INVALID_PICTURE_ID = 0x04
NEX_RET_INVALID_FONT_ID = 0x05
NEX_RET_INVALID_BAUD = 0x11
NEX_RET_INVALID_VARIABLE = 0x1A
NEX_RET_INVALID_OPERATION = 0x1B

# non standard define, but helpful in any case
NEX_END_CMD = b'\xFF\xFF\xFF'
